name: eAIP_JS
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.9.1
  - readline=8.0
  - setuptools=51.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020d
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - beautifulsoup4==4.9.3
    - bs4==0.0.1
    - camelot-py==0.8.2
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.1.2
    - cryptography==3.3.1
    - cssselect==1.1.0
    - distro==1.5.0
    - et-xmlfile==1.0.1
    - idna==2.10
    - jdcal==1.4.1
    - lxml==4.6.2
    - numpy==1.19.4
    - opencv-python==4.4.0.46
    - openpyxl==3.0.5
    - pandas==1.2.0
    - pdfminer-six==20201018
    - pdfquery==0.4.3
    - pycparser==2.20
    - pypdf2==1.26.0
    - pyquery==1.4.3
    - pytz==2020.5
    - requests==2.25.1
    - roman==3.3
    - six==1.15.0
    - sortedcontainers==2.3.0
    - soupsieve==2.1
    - tabula-py==2.2.0
    - urllib3==1.26.2
